favicon: /assets/images/favicon.svg
logo: /assets/images/photo.png

show_info: true
show_contacts: true

main_language_code: en
fullname: Ivan Zakharov
age: 18 y.o.
location: Moscow, Russia
language: Russian, English
bt_mailto: <a href="mailto:z4haroff.ivan@yandex.com">Send me <strong>Mail</strong></a>
bt_github: <a href="https://github.com/Zimovchik">Profile <strong>GitHub</strong></a>
bt_pdf: <a href="_">Download <strong>CV PDF</strong></a>

second_language_code: ru
second_fullname: Иван Захаров
second_age: 18 лет
second_location: Москва, Россия
second_language: Русский, Английский
second_bt_mailto: <a href="mailto:z4haroff.ivan@yandex.com">Написать на <strong>Почту</strong></a>
second_bt_github: <a href="https://github.com/Zimovchik">Профиль <strong>GitHub</strong></a>
second_bt_pdf: <a href="_">Скачать резюме<strong>PDF</strong></a>

show_branding: false
branding_link: 
branding_link_text: 
branding_favicon: 

remote_theme: annndruha/minimal-resume@v2.1.0
plugins:
- jekyll-remote-theme
